(ns agraph.coverage-test
  (:require [agraph.coverage :as coverage]
            [clojure.java.io :as io]
            [clojure.test :refer [deftest is]]))

(defn- temp-dir
  [prefix]
  (let [file (java.nio.file.Files/createTempDirectory
              prefix
              (make-array java.nio.file.attribute.FileAttribute 0))]
    (.getPath (.toFile file))))

(defn- spit-file!
  [root path content]
  (let [file (io/file root path)]
    (.mkdirs (.getParentFile file))
    (spit file content)
    (.getPath file)))

(defn- row-by
  [k value rows]
  (some #(when (= value (get % k)) %) rows))

(deftest project-coverage-reports-supported-and-skipped-source-types
  (let [root (temp-dir "agraph-coverage-repo")]
    (spit-file! root "src/app.py" "def main():\n    return 1\n")
    (spit-file! root "src/App.java" "package demo;\npublic class App {}\n")
    (spit-file! root "src/App.kt" "package demo\nclass App\n")
    (spit-file! root "src/App.swift" "struct App {}\n")
    (spit-file! root "src/App.cs" "namespace Demo;\npublic class App {}\n")
    (spit-file! root "src/App.csproj" "<Project><ItemGroup><PackageReference Include=\"Dapper\" /></ItemGroup></Project>\n")
    (spit-file! root "build.gradle" "rootProject.name = 'demo'\n")
    (spit-file! root "android/AndroidManifest.xml" "<manifest package=\"com.example\"><uses-permission android:name=\"android.permission.INTERNET\" /></manifest>\n")
    (spit-file! root "android/res/values/strings.xml" "<resources><string name=\"app_name\">Demo</string></resources>\n")
    (spit-file! root "android/res/layout/activity.xml" "<LinearLayout android:id=\"@+id/root\" />\n")
    (spit-file! root "android/res/navigation/main.xml" "<navigation android:id=\"@+id/main\" />\n")
    (spit-file! root "ios/Info.plist" "<plist><dict><key>CFBundleIdentifier</key><string>com.example</string></dict></plist>\n")
    (spit-file! root "ios/App.entitlements" "<plist><dict><key>aps-environment</key><string>development</string></dict></plist>\n")
    (spit-file! root "ios/Debug.xcconfig" "PRODUCT_BUNDLE_IDENTIFIER = com.example\n")
    (spit-file! root "ios/Podfile" "target 'Demo' do\n  pod 'Alamofire'\nend\n")
    (spit-file! root "ios/Package.swift" "let package = Package(name: \"Demo\")\n")
    (spit-file! root "ios/Demo.xcodeproj/project.pbxproj" "productName = Demo;\n")
    (spit-file! root "expo/app.json" "{\"expo\":{\"name\":\"Demo\",\"android\":{\"package\":\"com.example\"}}}\n")
    (spit-file! root "db/schema.prisma" "model User {\n  id String @id\n}\n")
    (spit-file! root "db/drizzle.config.ts" "export default { schema: './src/db/schema.ts' };\n")
    (spit-file! root "db/flyway.conf" "flyway.locations=filesystem:db/migration\n")
    (spit-file! root "db/liquibase.properties" "changeLogFile=db/changelog.xml\n")
    (spit-file! root "db/migration/V1__create_panels.sql" "create table panels (id text primary key);\n")
    (spit-file! root "db/changelog/db.changelog-master.yaml" "databaseChangeLog:\n  - changeSet:\n      id: create-panels\n")
    (spit-file! root "codegen/graphql-codegen.yml" "schema: ./contracts/schema.graphql\n")
    (spit-file! root "contracts/schema.graphql" "type Query { panel: Panel }\ntype Panel { id: ID! }\n")
    (spit-file! root "contracts/panel.proto" "syntax = \"proto3\";\npackage demo;\nmessage Panel { string id = 1; }\n")
    (spit-file! root "contracts/events.asyncapi.json" "{\"asyncapi\":\"3.0.0\",\"channels\":{\"panel.created\":{}},\"components\":{\"messages\":{\"PanelCreated\":{}},\"schemas\":{\"Panel\":{}}}}\n")
    (spit-file! root "contracts/panel.schema.json" "{\"$id\":\"panel\",\"properties\":{\"id\":{\"type\":\"string\"}},\"$defs\":{\"User\":{}}}\n")
    (spit-file! root "contracts/panel.avsc" "{\"type\":\"record\",\"name\":\"Panel\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"}]}\n")
    (spit-file! root "dbt/dbt_project.yml" "name: panels\nprofile: panels_profile\nmodel-paths:\n  - models\n")
    (spit-file! root "dbt/panel_orders.sql" "select * from {{ ref('panels') }}\n")
    (spit-file! root "dbt/packages.yml" "packages:\n  - package: dbt-labs/dbt_utils\n")
    (spit-file! root "dbt/profiles.yml" "panels:\n  target: dev\n  outputs:\n    dev:\n      type: postgres\n")
    (spit-file! root "dbt/models/schema.yml" "version: 2\nmodels:\n  - name: panel_orders\nsources:\n  - name: billing\n")
    (spit-file! root "notebooks/panel_analysis.ipynb" "{\"cells\":[{\"cell_type\":\"code\",\"source\":[\"print(1)\\n\"]}],\"metadata\":{\"kernelspec\":{\"name\":\"python3\"},\"language_info\":{\"name\":\"python\"}},\"nbformat\":4}\n")
    (spit-file! root ".devcontainer/devcontainer.json" "{\"image\":\"mcr.microsoft.com/devcontainers/base:ubuntu\",\"features\":{\"ghcr.io/devcontainers/features/node:1\":{}},\"runServices\":[\"db\"],\"forwardPorts\":[3000],\"postCreateCommand\":\"bb test\"}\n")
    (spit-file! root "infra/kustomize/kustomization.yaml" "resources:\n  - ../k8s/deployment.yaml\nimages:\n  - name: ghcr.io/acme/panels-web\nconfigMapGenerator:\n  - name: panels-config\n")
    (spit-file! root ".pre-commit-config.yaml" "repos:\n  - repo: https://github.com/pre-commit/pre-commit-hooks\n    rev: v4.6.0\n    hooks:\n      - id: trailing-whitespace\n")
    (spit-file! root ".github/CODEOWNERS" "* @acme/core\n/frontend/ @acme/web @acme/design\n")
    (spit-file! root "tasks/Taskfile.yml" "version: '3'\ntasks:\n  build:\n    deps: [lint]\n    cmds:\n      - bb test\n")
    (spit-file! root "tasks/justfile" "test: lint\n  bb test\n")
    (spit-file! root "build/rules/panels.bzl" "load(\"@rules_java//java:defs.bzl\", \"java_library\")\ndef panel_library(name):\n    pass\npanel_rule = rule(implementation = panel_library)\n")
    (spit-file! root ".tool-versions" "nodejs 20.11.1\npython 3.12.2\n")
    (spit-file! root ".node-version" "20.11.1\n")
    (spit-file! root ".python-version" "3.12.2\n")
    (spit-file! root ".ruby-version" "3.3.0\n")
    (spit-file! root "mise.toml" "[tools]\nnode = \"20.11.1\"\n[env]\nPANEL_ENV = \"dev\"\n[tasks.build]\nrun = \"bb test\"\n")
    (spit-file! root "pages/index.astro" "---\nimport Header from '../Header.astro';\n---\n<Header />\n")
    (spit-file! root "plugin/connector.php" "<?php\nnamespace Demo;\nclass Connector {}\n")
    (spit-file! root "framework/routes/web.php" "<?php\nRoute::get('/panels', [PanelController::class, 'index']);\n")
    (spit-file! root "framework/config/routes.yaml" "panel_show:\n  path: /panels/{id}\n  controller: App\\Controller\\PanelController::show\n")
    (spit-file! root ".github/ISSUE_TEMPLATE/bug_report.yml" "name: Bug report\nlabels: bug\n")
    (spit-file! root ".github/PULL_REQUEST_TEMPLATE.md" "# Summary\n- [ ] Tests updated\n")
    (spit-file! root ".github/FUNDING.yml" "github: acme\n")
    (spit-file! root "SECURITY.md" "# Security Policy\n")
    (spit-file! root "CONTRIBUTING.md" "# Contributing\n")
    (spit-file! root "languages/messages.po" "msgid \"Hello\"\nmsgstr \"Hei\"\n")
    (spit-file! root "assets/logo.svg" "<svg id=\"logo\"></svg>\n")
    (spit-file! root "assets/hero.png" "png\n")
    (spit-file! root "assets/photo.jpg" "jpg\n")
    (spit-file! root "assets/preview.webp" "webp\n")
    (spit-file! root "assets/favicon.ico" "ico\n")
    (spit-file! root "assets/fonts/outfit.ttf" "ttf\n")
    (spit-file! root "languages/messages.mo" "mo\n")
    (spit-file! root "wrangler.ops.jsonc" "{ // comment\n \"name\": \"demo\"\n}\n")
    (spit-file! root "infra/support.env.example" "SUPPORT_URL=https://example.com\n")
    (spit-file! root "public/index.html" "<!doctype html><main id=\"app\"></main>\n")
    (spit-file! root "plugin/readme.txt" "Demo plugin\n")
    (spit-file! root "README.md" "# Demo\n")
    (spit-file! root "LICENSE" "MIT\n")
    (spit-file! root "resources/vendor/cytoscape.LICENSE" "Vendor license\n")
    (spit-file! root "docs/release-notes.adoc" "= Release Notes\n\n== Runtime\n")
    (spit-file! root "docs/changes.rst" "Changes\n=======\n\nRuntime notes\n")
    (spit-file! root "infra/flake.nix" "{ description = \"Demo\"; }\n")
    (spit-file! root "scripts/run-server.sh.in" "#!/bin/sh\nexec demo\n")
    (spit-file! root "bin/tool" "#!/usr/bin/env bash\nexec demo\n")
    (spit-file! root "tests/expected/result.out" "ok\n")
    (spit-file! root "web/app.ts" "export const value = 1;\n")
    (spit-file! root "web/widget.vue" "<template><main /></template>\n<script>export const value = 1;</script>\n")
    (spit-file! root "web/widget.svelte" "<script>export const value = 1;</script>\n")
    (spit-file! root "workspace/package.json" "{\"name\":\"demo\",\"dependencies\":{\"react\":\"latest\"}}\n")
    (spit-file! root "workspace/deno.json" "{\"imports\":{\"@std/path\":\"jsr:@std/path@^1.0.0\"}}\n")
    (spit-file! root "workspace/composer.json" "{\"name\":\"acme/panels\",\"require\":{\"symfony/console\":\"^7.0\"}}\n")
    (spit-file! root "workspace/go.work" "go 1.22\nuse ./services/api\n")
    (spit-file! root "workspace/pnpm-workspace.yaml" "packages:\n  - apps/*\n")
    (spit-file! root "workspace/turbo.json" "{\"tasks\":{\"build\":{}}}\n")
    (spit-file! root "workspace/nx.json" "{\"targetDefaults\":{\"build\":{}},\"projects\":{\"web\":{}}}\n")
    (spit-file! root "workspace/lerna.json" "{\"packages\":[\"packages/*\"],\"npmClient\":\"pnpm\"}\n")
    (spit-file! root "workspace/rush.json" "{\"projects\":[{\"packageName\":\"@acme/web\"}],\"pnpmVersion\":\"9.0.0\"}\n")
    (spit-file! root "python/Pipfile" "[packages]\nrequests = \">=2\"\n")
    (spit-file! root "python/setup.cfg" "[metadata]\nname = panels-py\n[options]\ninstall_requires =\n  requests>=2\n")
    (spit-file! root "python/setup.py" "from setuptools import setup\nsetup(name=\"panels-setup\", install_requires=[\"fastapi\"])\n")
    (spit-file! root "src/ruby/panel_service.rb" "module Demo\n  class PanelService\n  end\nend\n")
    (spit-file! root "src/ruby/Rakefile" "task :build\n")
    (spit-file! root "src/ruby/Gemfile" "gem \"rails\"\n")
    (spit-file! root "src/ruby/panels.gemspec" "Gem::Specification.new { |spec| spec.name = \"panels\" }\n")
    (spit-file! root "src/groovy/PanelService.groovy" "package demo\nclass PanelService {}\n")
    (spit-file! root "packaging/homebrew/Formula/demo.rb.template" "class Demo < Formula\nend\n")
    (spit-file! root "src/native/panel_service.cpp" "#include <vector>\nint build_panel() { return 1; }\n")
    (spit-file! root "src/native/panel_service.hpp" "class PanelService {};\n")
    (spit-file! root "mobile/ios/PanelService.m" "#import <Foundation/Foundation.h>\n@implementation PanelService\n@end\n")
    (spit-file! root "flutter/lib/panel_store.dart" "class PanelStore {}\n")
    (spit-file! root "flutter/pubspec.yaml" "name: panels_flutter\ndependencies:\n  http: ^1.0.0\n")
    (spit-file! root "src/scala/PanelService.scala" "package demo\nclass PanelService\n")
    (spit-file! root "src/scala/build.sbt" "name := \"demo\"\n")
    (spit-file! root "src/elixir/panel_service.ex" "defmodule Demo.PanelService do\nend\n")
    (spit-file! root "src/elixir/mix.exs" "defmodule Demo.MixProject do\nend\n")
    (spit-file! root "src/erlang/panel_service.erl" "-module(panel_service).\n")
    (spit-file! root "src/erlang/rebar.config" "{deps, []}.\n")
    (spit-file! root "src/lua/panel_service.lua" "local M = {}\n")
    (spit-file! root "src/r/panel_service.R" "load_panel <- function(id) id\n")
    (spit-file! root "src/r/DESCRIPTION" "Package: panels\nImports: dplyr\n")
    (spit-file! root "src/r/NAMESPACE" "import(dplyr)\n")
    (spit-file! root "src/julia/PanelService.jl" "module PanelService\nend\n")
    (spit-file! root "src/julia/Project.toml" "name = \"Panels\"\n[deps]\nDataFrames = \"uuid\"\n")
    (spit-file! root "src/ocaml/panel_service.ml" "open Core\nlet load_panel id = id\n")
    (spit-file! root "src/ocaml/panel_service.mli" "val load_panel : string -> string\n")
    (spit-file! root "src/perl/PanelService.pm" "package PanelService;\nsub load_panel {}\n")
    (spit-file! root "src/perl/cpanfile" "requires 'Mojolicious';\n")
    (spit-file! root "src/haskell/PanelService.hs" "module PanelService where\n")
    (spit-file! root "src/haskell/panels.cabal" "name: panels\n")
    (spit-file! root "src/haskell/stack.yaml" "packages:\n  panels: .\n")
    (spit-file! root "src/odin/panel_service.odin" "package panels\nload_panel :: proc() {}\n")
    (spit-file! root "src/odin/ols.json" "{\"name\":\"panels-odin\",\"collections\":{\"panels\":\"src/odin\"}}\n")
    (spit-file! root "src/zig/panel_service.zig" "pub fn loadPanel() void {}\n")
    (spit-file! root "tooling/jest.config.js" "module.exports = { testEnvironment: \"jsdom\" };\n")
    (spit-file! root "tooling/playwright.config.ts" "export default { testDir: \"./e2e\" };\n")
    (spit-file! root "tooling/eslint.config.js" "export default [{ rules: { semi: \"error\" } }];\n")
    (spit-file! root ".prettierrc" "{\"semi\": false}\n")
    (spit-file! root "tooling/stylelint.config.js" "module.exports = { extends: [\"stylelint-config-standard\"] };\n")
    (spit-file! root "tooling/tsconfig.json" "{\"extends\":\"./tsconfig.base.json\"}\n")
    (spit-file! root "tooling/vite.config.ts" "import react from '@vitejs/plugin-react';\n")
    (spit-file! root "tooling/webpack.config.js" "module.exports = { entry: './src/index.ts' };\n")
    (spit-file! root "tooling/tailwind.config.js" "module.exports = { content: ['./src/**/*.tsx'] };\n")
    (spit-file! root "tooling/pytest.ini" "[pytest]\ntestpaths = tests\n")
    (spit-file! root ".github/dependabot.yml" "version: 2\nupdates:\n  - package-ecosystem: npm\n")
    (spit-file! root ".storybook/main.ts" "export default { stories: ['../src/**/*.stories.tsx'] };\n")
    (spit-file! root "tooling/renovate.json" "{\"extends\":[\"config:recommended\"]}\n")
    (spit-file! root ".editorconfig" "root = true\nindent_style = space\n")
    (spit-file! root "infra/docker-compose.yml" "services:\n  web:\n    image: ghcr.io/acme/web:latest\n    build: ./web\n")
    (spit-file! root "infra/chart/Chart.yaml" "apiVersion: v2\nname: panels\nversion: 0.1.0\n")
    (spit-file! root "infra/k8s/deployment.yaml" "kind: Deployment\nmetadata:\n  name: panels-web\n")
    (spit-file! root "infra/k8s/crd.yaml" "apiVersion: apiextensions.k8s.io/v1\nkind: CustomResourceDefinition\nmetadata:\n  name: panels.example.com\n")
    (spit-file! root "infra/k8s/crossplane.yaml" "apiVersion: s3.aws.upbound.io/v1beta1\nkind: Bucket\nmetadata:\n  name: panel-assets\nspec:\n  providerConfigRef:\n    name: aws-prod\n")
    (spit-file! root "infra/k8s/argocd-application.yaml" "apiVersion: argoproj.io/v1alpha1\nkind: Application\nmetadata:\n  name: panels\n")
    (spit-file! root "infra/chart/templates/deployment.yaml" "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{ include \"panels.fullname\" . }}\n")
    (spit-file! root "infra/cloudformation.json" "{\"Resources\":{\"PanelQueue\":{\"Type\":\"AWS::SQS::Queue\"}}}\n")
    (spit-file! root "ops/cloudformation.yaml" "AWSTemplateFormatVersion: \"2010-09-09\"\nResources:\n  PanelBucket:\n    Type: AWS::S3::Bucket\n")
    (spit-file! root "ops/Pulumi.yaml" "name: panels-infra\nruntime: nodejs\n")
    (spit-file! root "ops/playbook.yaml" "- hosts: web\n  tasks:\n    - name: Install nginx\n")
    (spit-file! root "ops/nginx.conf" "server {\n  listen 8080;\n}\n")
    (spit-file! root "ops/panels.service" "[Service]\nExecStart=/usr/bin/panels-worker\n")
    (spit-file! root "web/widget.wasm" "\000asm\n")
    (spit-file! root "package-lock.json" "{}\n")
    (spit-file! root "pnpm-lock.yaml" "packages:\n  react@19.1.0:\n")
    (spit-file! root "yarn.lock" "\"react@^19.0.0\":\n  version \"19.1.0\"\n")
    (spit-file! root "Gemfile.lock" "GEM\n  specs:\n    rails (7.1.0)\n")
    (spit-file! root "poetry.lock" "[[package]]\nname = \"requests\"\nversion = \"2.31.0\"\n")
    (spit-file! root "uv.lock" "[[package]]\nname = \"ruff\"\nversion = \"0.5.0\"\n")
    (spit-file! root "pubspec.lock" "packages:\n  http:\n    version: \"1.2.0\"\n")
    (spit-file! root "composer.lock" "{\"packages\":[{\"name\":\"symfony/console\",\"version\":\"v7.0.0\"}]}\n")
    (spit-file! root "Pipfile.lock" "{\"default\":{\"flask\":{\"version\":\"==3.0.0\"}}}\n")
    (spit-file! root "mix.lock" "%{\"plug\": {:hex, :plug, \"1.15.3\", \"checksum\", [], \"hexpm\", \"checksum\"}}\n")
    (spit-file! root "requirements.txt" "django==5.0.0\n")
    (spit-file! root "bun.lock" "{\"packages\":{\"react\":\"19.1.0\"}}\n")
    (spit-file! root ".github/workflows/ci.yml" "name: ci\n")
    (spit-file! root "Jenkinsfile" "pipeline { stages { stage('test') { steps { sh 'bb test' } } } }\n")
    (spit-file! root "azure-pipelines.yml" "trigger: [main]\njobs:\n  - job: test\n")
    (spit-file! root "Makefile" "test:\n\tbb test\n")
    (spit-file! root "build/toolchain.cmake" "add_library(shared src/shared.cpp)\n")
    (spit-file! root "build/BUCK" "cxx_library(\n    name = \"core\",\n)\n")
    (spit-file! root "target/generated.clj" "(ns generated)\n")
    (spit-file! root "node_modules/pkg/index.js" "module.exports = {}\n")
    (let [report (coverage/project-coverage
                  {:id "fixture"
                   :repos [{:id "app"
                            :root root
                            :role :application}]})]
      (is (= coverage/schema (:schema report)))
      (is (= {:files 172
              :supported 171
              :skipped 1}
             (select-keys (:totals report) [:files :supported :skipped])))
      (is (= 3 (:count (row-by :kind "build" (:files-by-kind report)))))
      (is (= 3 (:count (row-by :kind "ci" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "apple-config" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "astro" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "codegen-config" (:files-by-kind report)))))
      (is (= 3 (:count (row-by :kind "db-config" (:files-by-kind report)))))
      (is (= 2 (:count (row-by :kind "db-migration" (:files-by-kind report)))))
      (is (= 12 (:count (row-by :kind "dependency-lock" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "java" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "groovy" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "kotlin" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "swift" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "objective-c" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "dotnet" (:files-by-kind report)))))
      (is (= 3 (:count (row-by :kind "ruby" (:files-by-kind report)))))
      (is (= 2 (:count (row-by :kind "cpp" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "dart" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "scala" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "elixir" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "erlang" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "lua" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "r" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "julia" (:files-by-kind report)))))
      (is (= 2 (:count (row-by :kind "ocaml" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "perl" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "haskell" (:files-by-kind report)))))
      (is (= 2 (:count (row-by :kind "odin" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "zig" (:files-by-kind report)))))
      (is (= 3 (:count (row-by :kind "test-config" (:files-by-kind report)))))
      (is (= 11 (:count (row-by :kind "tool-config" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "compose" (:files-by-kind report)))))
      (is (= 2 (:count (row-by :kind "helm" (:files-by-kind report)))))
      (is (= 6 (:count (row-by :kind "ops-config" (:files-by-kind report)))))
      (is (= 5 (:count (row-by :kind "yaml" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "graphql" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "asyncapi" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "json-schema" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "avro" (:files-by-kind report)))))
      (is (= 2 (:count (row-by :kind "php" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "prisma" (:files-by-kind report)))))
      (is (= 4 (:count (row-by :kind "dbt" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "notebook" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "devcontainer" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "kustomize" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "pre-commit-config" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "codeowners" (:files-by-kind report)))))
      (is (= 2 (:count (row-by :kind "task-runner" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "starlark" (:files-by-kind report)))))
      (is (= 5 (:count (row-by :kind "tool-version-config" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "sql" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "protobuf" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "gettext" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "gettext-binary" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "svg" (:files-by-kind report)))))
      (is (= 4 (:count (row-by :kind "image-asset" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "font-asset" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "env" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "html" (:files-by-kind report)))))
      (is (= 2 (:count (row-by :kind "shell" (:files-by-kind report)))))
      (is (= 2 (:count (row-by :kind "text" (:files-by-kind report)))))
      (is (= 2 (:count (row-by :kind "config" (:files-by-kind report)))))
      (is (= 33 (:count (row-by :kind "manifest" (:files-by-kind report)))))
      (is (= 5 (:count (row-by :kind "governance" (:files-by-kind report)))))
      (is (= 3 (:count (row-by :kind "xml" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "python" (:files-by-kind report)))))
      (is (= 5 (:count (row-by :kind "doc" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "typescript" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "vue" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :kind "svelte" (:files-by-kind report)))))
      (is (= 1 (:count (row-by :ext ".wasm" (:skipped-by-extension report)))))
      (is (some #(and (= "python" (:kind %))
                      (= 1 (:files %))
                      (string? (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "java" (:kind %))
                      (= "java/v2" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "groovy" (:kind %))
                      (= "groovy/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "kotlin" (:kind %))
                      (= "kotlin/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "swift" (:kind %))
                      (= "swift/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "objective-c" (:kind %))
                      (= "objective-c/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "dotnet" (:kind %))
                      (= "dotnet/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "ruby" (:kind %))
                      (= "ruby/v1" (:extractor-version %))
                      (= 3 (:files %)))
                (:extractors report)))
      (is (some #(and (= "cpp" (:kind %))
                      (= "cpp/v1" (:extractor-version %))
                      (= 2 (:files %)))
                (:extractors report)))
      (is (some #(and (= "dart" (:kind %))
                      (= "dart/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "scala" (:kind %))
                      (= "scala/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "elixir" (:kind %))
                      (= "elixir/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "erlang" (:kind %))
                      (= "erlang/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "lua" (:kind %))
                      (= "lua/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "r" (:kind %))
                      (= "r/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "julia" (:kind %))
                      (= "julia/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "ocaml" (:kind %))
                      (= "ocaml/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "perl" (:kind %))
                      (= "perl/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "haskell" (:kind %))
                      (= "haskell/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "odin" (:kind %))
                      (= "odin/v1" (:extractor-version %))
                      (= 2 (:files %)))
                (:extractors report)))
      (is (some #(and (= "zig" (:kind %))
                      (= "zig/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "test-config" (:kind %))
                      (= "test-config/v1" (:extractor-version %))
                      (= 3 (:files %)))
                (:extractors report)))
      (is (some #(and (= "tool-config" (:kind %))
                      (= "tool-config/v1" (:extractor-version %))
                      (= 11 (:files %)))
                (:extractors report)))
      (is (some #(and (= "compose" (:kind %))
                      (= "compose/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "helm" (:kind %))
                      (= "helm/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "ops-config" (:kind %))
                      (= "ops-config/v1" (:extractor-version %))
                      (= 6 (:files %)))
                (:extractors report)))
      (is (some #(and (= "yaml" (:kind %))
                      (= "yaml/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "apple-config" (:kind %))
                      (= "apple-config/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "codegen-config" (:kind %))
                      (= "codegen-config/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "db-config" (:kind %))
                      (= "db-config/v1" (:extractor-version %))
                      (= 3 (:files %)))
                (:extractors report)))
      (is (some #(and (= "db-migration" (:kind %))
                      (= "db-migration/v1" (:extractor-version %))
                      (= 2 (:files %)))
                (:extractors report)))
      (is (some #(and (= "dependency-lock" (:kind %))
                      (= "dependency-lock/v1" (:extractor-version %))
                      (= 12 (:files %)))
                (:extractors report)))
      (is (some #(and (= "image-asset" (:kind %))
                      (= "asset/v1" (:extractor-version %))
                      (= 4 (:files %)))
                (:extractors report)))
      (is (some #(and (= "font-asset" (:kind %))
                      (= "asset/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "gettext-binary" (:kind %))
                      (= "gettext-binary/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "astro" (:kind %))
                      (= "astro/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "graphql" (:kind %))
                      (= "graphql/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "asyncapi" (:kind %))
                      (= "asyncapi/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "json-schema" (:kind %))
                      (= "json-schema/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "avro" (:kind %))
                      (= "avro/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "php" (:kind %))
                      (= "php/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "prisma" (:kind %))
                      (= "prisma/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "dbt" (:kind %))
                      (= "dbt/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "governance" (:kind %))
                      (= "governance/v1" (:extractor-version %))
                      (= 5 (:files %)))
                (:extractors report)))
      (is (some #(and (= "notebook" (:kind %))
                      (= "notebook/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "devcontainer" (:kind %))
                      (= "devcontainer/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "kustomize" (:kind %))
                      (= "kustomize/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "pre-commit-config" (:kind %))
                      (= "pre-commit-config/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "codeowners" (:kind %))
                      (= "codeowners/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "task-runner" (:kind %))
                      (= "task-runner/v1" (:extractor-version %))
                      (= 2 (:files %)))
                (:extractors report)))
      (is (some #(and (= "starlark" (:kind %))
                      (= "starlark/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "tool-version-config" (:kind %))
                      (= "tool-version-config/v1" (:extractor-version %))
                      (= 5 (:files %)))
                (:extractors report)))
      (is (some #(and (= "sql" (:kind %))
                      (= "sql/v2" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "protobuf" (:kind %))
                      (= "protobuf/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "gettext" (:kind %))
                      (= "gettext/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "svg" (:kind %))
                      (= "svg/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "env" (:kind %))
                      (= "env/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "html" (:kind %))
                      (= "html/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "text" (:kind %))
                      (= "text/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "shell" (:kind %))
                      (= "shell/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "manifest" (:kind %))
                      (= "manifest/v2" (:extractor-version %))
                      (= 33 (:files %)))
                (:extractors report)))
      (is (some #(and (= "xml" (:kind %))
                      (= "xml/v1" (:extractor-version %))
                      (= 3 (:files %)))
                (:extractors report)))
      (is (some #(and (= "ci" (:kind %))
                      (= "ci/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "build" (:kind %))
                      (= "build/v1" (:extractor-version %))
                      (= 3 (:files %)))
                (:extractors report)))
      (is (some #(and (= "vue" (:kind %))
                      (= "vue/v1" (:extractor-version %)))
                (:extractors report)))
      (is (some #(and (= "svelte" (:kind %))
                      (= "svelte/v1" (:extractor-version %)))
                (:extractors report)))
      (is (= 0 (get-in report [:diagnostics :total]))))))
