(ns agraph.watch-test
  (:require [agraph.watch :as watch]
            [clojure.java.shell :as shell]
            [clojure.test :refer [deftest is]]))

(deftest watchable-path-detects-supported-non-ignored-files
  (is (watch/watchable-path? "src/app.clj"))
  (is (watch/watchable-path? "Dockerfile"))
  (is (watch/watchable-path? "Containerfile"))
  (is (watch/watchable-path? "Procfile"))
  (is (watch/watchable-path? "infra/deploy.yaml"))
  (is (not (watch/watchable-path? ".dev/report.json")))
  (is (not (watch/watchable-path? "target/classes/app.clj")))
  (is (watch/watchable-path? "package-lock.json"))
  (is (watch/watchable-path? "Cargo.lock"))
  (is (watch/watchable-path? "go.sum"))
  (is (watch/watchable-path? "pnpm-lock.yaml"))
  (is (watch/watchable-path? "yarn.lock"))
  (is (watch/watchable-path? "Gemfile.lock"))
  (is (watch/watchable-path? "poetry.lock"))
  (is (watch/watchable-path? "uv.lock"))
  (is (watch/watchable-path? "composer.lock"))
  (is (watch/watchable-path? "Pipfile.lock"))
  (is (watch/watchable-path? "mix.lock"))
  (is (watch/watchable-path? "requirements.txt"))
  (is (watch/watchable-path? "bun.lock"))
  (is (not (watch/watchable-path? "bun.lockb")))
  (is (watch/watchable-path? ".env"))
  (is (watch/watchable-path? "apps/api/.env.local"))
  (is (watch/watchable-path? "config/prod.env"))
  (is (watch/watchable-path? "infra/support.env.example"))
  (is (watch/watchable-path? "ci/Jenkinsfile"))
  (is (watch/watchable-path? "ci/azure-pipelines.yml"))
  (is (watch/watchable-path? "ci/.circleci/config.yml"))
  (is (watch/watchable-path? "ci/.buildkite/pipeline.yml"))
  (is (watch/watchable-path? "ci/.drone.yml"))
  (is (watch/watchable-path? "ci/.woodpecker.yml"))
  (is (watch/watchable-path? "web/component.vue"))
  (is (watch/watchable-path? "web/component.svelte"))
  (is (watch/watchable-path? "android/MainActivity.kt"))
  (is (watch/watchable-path? "ios/AppDelegate.swift"))
  (is (watch/watchable-path? "android/res/layout/activity.xml"))
  (is (watch/watchable-path? "ios/Debug.xcconfig"))
  (is (watch/watchable-path? "ios/App.entitlements"))
  (is (watch/watchable-path? "mobile/capacitor.config.ts"))
  (is (watch/watchable-path? "mobile/tauri.conf.json"))
  (is (watch/watchable-path? "db/schema.prisma"))
  (is (watch/watchable-path? "dbt/dbt_project.yml"))
  (is (watch/watchable-path? "dbt/panel_orders.sql"))
  (is (watch/watchable-path? "notebooks/panel_analysis.ipynb"))
  (is (watch/watchable-path? ".devcontainer/devcontainer.json"))
  (is (watch/watchable-path? "infra/kustomize/kustomization.yaml"))
  (is (watch/watchable-path? ".pre-commit-config.yaml"))
  (is (watch/watchable-path? ".github/CODEOWNERS"))
  (is (watch/watchable-path? ".github/ISSUE_TEMPLATE/bug_report.yml"))
  (is (watch/watchable-path? ".github/PULL_REQUEST_TEMPLATE.md"))
  (is (watch/watchable-path? ".github/FUNDING.yml"))
  (is (watch/watchable-path? "SECURITY.md"))
  (is (watch/watchable-path? "CONTRIBUTING.md"))
  (is (watch/watchable-path? "tasks/Taskfile.yml"))
  (is (watch/watchable-path? "tasks/justfile"))
  (is (watch/watchable-path? "build/rules/panels.bzl"))
  (is (watch/watchable-path? ".tool-versions"))
  (is (watch/watchable-path? ".node-version"))
  (is (watch/watchable-path? ".python-version"))
  (is (watch/watchable-path? ".ruby-version"))
  (is (watch/watchable-path? "mise.toml"))
  (is (watch/watchable-path? "db/flyway.conf"))
  (is (watch/watchable-path? "db/liquibase.properties"))
  (is (watch/watchable-path? "dbt/packages.yml"))
  (is (watch/watchable-path? "dbt/profiles.yml"))
  (is (watch/watchable-path? "dbt/models/schema.yml"))
  (is (watch/watchable-path? "db/migration/V1__create_panels.sql"))
  (is (watch/watchable-path? "db/changelog/db.changelog-master.yaml"))
  (is (watch/watchable-path? "codegen/graphql-codegen.yml"))
  (is (watch/watchable-path? "contracts/events.asyncapi.json"))
  (is (watch/watchable-path? "contracts/panel.schema.json"))
  (is (watch/watchable-path? "contracts/panel.avsc"))
  (is (watch/watchable-path? "contracts/panels.avdl"))
  (is (watch/watchable-path? "workspace/package.json"))
  (is (watch/watchable-path? "workspace/composer.json"))
  (is (watch/watchable-path? "workspace/go.work"))
  (is (watch/watchable-path? "workspace/pnpm-workspace.yaml"))
  (is (watch/watchable-path? "workspace/turbo.json"))
  (is (watch/watchable-path? "src/ruby/panel_service.rb"))
  (is (watch/watchable-path? "src/ruby/Rakefile"))
  (is (watch/watchable-path? "src/ruby/Gemfile"))
  (is (watch/watchable-path? "src/ruby/panels.gemspec"))
  (is (watch/watchable-path? "LICENSE"))
  (is (watch/watchable-path? "resources/vendor/cytoscape.LICENSE"))
  (is (watch/watchable-path? "packaging/homebrew/Formula/demo.rb.template"))
  (is (watch/watchable-path? "src/native/panel_service.cpp"))
  (is (watch/watchable-path? "src/native/panel_service.hpp"))
  (is (watch/watchable-path? "flutter/lib/panel_store.dart"))
  (is (watch/watchable-path? "flutter/pubspec.yaml"))
  (is (watch/watchable-path? "flutter/pubspec.lock"))
  (is (watch/watchable-path? "src/scala/PanelService.scala"))
  (is (watch/watchable-path? "src/scala/build.sbt"))
  (is (watch/watchable-path? "src/elixir/panel_service.ex"))
  (is (watch/watchable-path? "src/elixir/mix.exs"))
  (is (watch/watchable-path? "src/erlang/panel_service.erl"))
  (is (watch/watchable-path? "src/erlang/rebar.config"))
  (is (watch/watchable-path? "src/lua/panel_service.lua"))
  (is (watch/watchable-path? "src/r/panel_service.R"))
  (is (watch/watchable-path? "src/r/DESCRIPTION"))
  (is (watch/watchable-path? "src/r/NAMESPACE"))
  (is (watch/watchable-path? "src/julia/PanelService.jl"))
  (is (watch/watchable-path? "src/julia/Project.toml"))
  (is (watch/watchable-path? "src/perl/PanelService.pm"))
  (is (watch/watchable-path? "src/perl/cpanfile"))
  (is (watch/watchable-path? "src/haskell/PanelService.hs"))
  (is (watch/watchable-path? "src/haskell/panels.cabal"))
  (is (watch/watchable-path? "src/haskell/stack.yaml"))
  (is (watch/watchable-path? "src/odin/panel_service.odin"))
  (is (watch/watchable-path? "src/odin/ols.json"))
  (is (watch/watchable-path? "src/zig/panel_service.zig"))
  (is (watch/watchable-path? "assets/hero.png"))
  (is (watch/watchable-path? "assets/photo.jpg"))
  (is (watch/watchable-path? "assets/preview.webp"))
  (is (watch/watchable-path? "assets/favicon.ico"))
  (is (watch/watchable-path? "assets/fonts/outfit.ttf"))
  (is (watch/watchable-path? "languages/messages.mo"))
  (is (watch/watchable-path? "tooling/jest.config.js"))
  (is (watch/watchable-path? "tooling/playwright.config.ts"))
  (is (watch/watchable-path? "tooling/pytest.ini"))
  (is (watch/watchable-path? "tooling/eslint.config.js"))
  (is (watch/watchable-path? "tooling/tsconfig.json"))
  (is (watch/watchable-path? "tooling/vite.config.ts"))
  (is (watch/watchable-path? "tooling/webpack.config.js"))
  (is (watch/watchable-path? "tooling/tailwind.config.js"))
  (is (watch/watchable-path? ".prettierrc"))
  (is (watch/watchable-path? ".editorconfig"))
  (is (watch/watchable-path? ".vscode/settings.json"))
  (is (watch/watchable-path? ".vscode/tasks.json"))
  (is (watch/watchable-path? ".vscode/extensions.json"))
  (is (watch/watchable-path? "panels.code-workspace"))
  (is (watch/watchable-path? ".github/dependabot.yml"))
  (is (watch/watchable-path? ".storybook/main.ts"))
  (is (watch/watchable-path? "docs/components.mdx"))
  (is (watch/watchable-path? "docs/docusaurus.config.ts"))
  (is (watch/watchable-path? "docs/sidebars.ts"))
  (is (watch/watchable-path? "docs/mkdocs.yml"))
  (is (watch/watchable-path? "src/content.config.ts"))
  (is (watch/watchable-path? "src/content/config.ts"))
  (is (watch/watchable-path? "docs/.vitepress/config.ts"))
  (is (watch/watchable-path? "docs/.vitepress/config/index.mts"))
  (is (watch/watchable-path? "docs/sphinx/conf.py"))
  (is (watch/watchable-path? "docs/sphinx/index.rst"))
  (is (watch/watchable-path? "docs/nextra/next.config.mjs"))
  (is (watch/watchable-path? "docs/nextra/content/_meta.ts"))
  (is (watch/watchable-path? "sbom/cyclonedx.json"))
  (is (watch/watchable-path? "sbom/spdx.json"))
  (is (watch/watchable-path? "src/ui/Button.stories.tsx"))
  (is (watch/watchable-path? "tooling/renovate.json"))
  (is (not (watch/watchable-path? "tooling/.prettierrc")))
  (is (watch/watchable-path? "tooling/stylelint.config.js"))
  (is (watch/watchable-path? "infra/docker-compose.yml"))
  (is (watch/watchable-path? "infra/chart/Chart.yaml"))
  (is (watch/watchable-path? "infra/chart/templates/deployment.yaml"))
  (is (watch/watchable-path? "infra/k8s/deployment.yaml"))
  (is (watch/watchable-path? "infra/k8s/crd.yaml"))
  (is (watch/watchable-path? "infra/k8s/crossplane.yaml"))
  (is (watch/watchable-path? "infra/k8s/argocd-application.yaml"))
  (is (watch/watchable-path? "infra/cloudformation.json"))
  (is (watch/watchable-path? "ops/cloudformation.yaml"))
  (is (watch/watchable-path? "ops/Pulumi.yaml"))
  (is (watch/watchable-path? "ops/playbook.yaml"))
  (is (watch/watchable-path? "ops/nginx.conf"))
  (is (watch/watchable-path? "ops/panels.service"))
  (is (watch/watchable-path? "framework/config/routes.yaml"))
  (is (watch/watchable-path? "framework/routes/web.php"))
  (is (watch/watchable-path? "python/Pipfile"))
  (is (watch/watchable-path? "python/setup.cfg"))
  (is (watch/watchable-path? "python/setup.py"))
  (is (watch/watchable-path? "build/toolchain.cmake"))
  (is (watch/watchable-path? "build/BUCK")))

(deftest coalesce-events-keeps-distinct-watchable-paths
  (is (= ["README.md" "src/app.clj"]
         (watch/coalesce-events ["src/app.clj"
                                 "src/app.clj"
                                 ".git/index"
                                 "README.md"
                                 "node_modules/pkg/index.js"]))))

(deftest sync-args-use-graph-maintenance-profile-by-default
  (is (= ["sync" "project.edn" "--repo" "app" "--check"]
         (watch/sync-args {:config-path "project.edn"
                           :repo-id "app"})))
  (is (= ["sync" "project.edn" "--repo" "app" "--check"
          "--map" "agraph.map.json" "--query-index"]
         (watch/sync-args {:config-path "project.edn"
                           :repo-id "app"
                           :map-path "agraph.map.json"
                           :query-index? true}))))

(deftest refresh-runs-agraph-sync-command
  (let [calls (atom [])]
    (with-redefs [shell/sh (fn [& argv]
                             (swap! calls conj (vec argv))
                             {:exit 0 :out "ok" :err ""})]
      (is (= {:exit 0 :out "ok" :err ""}
             (watch/refresh! {:agraph-bin "bin/agraph"
                              :config-path "project.edn"
                              :repo-id "app"
                              :map-path "agraph.map.json"})))
      (is (= [["bin/agraph" "sync" "project.edn" "--repo" "app" "--check"
               "--map" "agraph.map.json"]]
             @calls)))))
